name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Permite execução manual

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
        
      - name: Cypress Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-
      
      - name: Verify Cypress Installation
        run: |
          npx cypress install --force
          npx cypress verify
        continue-on-error: false
            
      - name: Run Cypress Tests (E2E + Performance)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: false
          spec: 'cypress/e2e/**/*.cy.js'
          config-file: cypress.config.ci.js
          
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ github.run_id }}
          path: cypress/screenshots
          if-no-files-found: ignore
          
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ github.run_id }}
          path: cypress/videos
          if-no-files-found: ignore

      - name: Generate Detailed Reports
        if: always()
        continue-on-error: true
        run: |
          echo "🚀 Gerando relatórios detalhados..."
          
          # Cria diretório de relatórios se não existir
          mkdir -p cypress/reports
          
          # Gera relatório de performance detalhado
          echo "📊 Performance Report - $(date)" > performance-report-${{ github.run_id }}.txt
          echo "Branch: ${{ github.ref }}" >> performance-report-${{ github.run_id }}.txt
          echo "Commit: ${{ github.sha }}" >> performance-report-${{ github.run_id }}.txt
          echo "Workflow: ${{ github.workflow }}" >> performance-report-${{ github.run_id }}.txt
          
          # Gera relatório combinado com todos os testes
          echo "🔄 Gerando relatório combinado..."
          node scripts/combine-reports.js || echo "⚠️ Relatório combinado não gerado"
          
          # Gera relatório HTML detalhado
          echo "📝 Gerando relatório HTML..."
          node scripts/generate-report.js || echo "⚠️ Relatório HTML não gerado"
          
      - name: Upload Performance Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-report-${{ github.run_id }}
          path: performance-report-${{ github.run_id }}.txt
          if-no-files-found: ignore

      - name: Upload Mochawesome Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-reports-${{ github.run_id }}
          path: mochawesome-report/
          if-no-files-found: ignore

      - name: Upload Detailed Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: detailed-reports-${{ github.run_id }}
          path: cypress/reports/
          if-no-files-found: ignore

  # Job adicional para testes de performance (executa apenas em pushes para main)
  # NOTA: Os testes de performance já são executados no job principal acima
  # Este job adicional é para métricas específicas e relatórios detalhados
  performance-tests:
    runs-on: ubuntu-latest
    needs: cypress-run
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run Performance Tests
        run: |
          npm run test:performance
          
      - name: Generate Performance Metrics
        run: |
          echo "🚀 Performance Metrics Report - $(date)" > performance-metrics-${{ github.run_id }}.txt
          echo "Branch: ${{ github.ref }}" >> performance-metrics-${{ github.run_id }}.txt
          echo "Commit: ${{ github.sha }}" >> performance-metrics-${{ github.run_id }}.txt
          echo "Workflow: ${{ github.workflow }}" >> performance-metrics-${{ github.run_id }}.txt
          echo "Status: ${{ job.status }}" >> performance-metrics-${{ github.run_id }}.txt
          echo "" >> performance-metrics-${{ github.run_id }}.txt
          echo "📊 Performance Test Results:" >> performance-metrics-${{ github.run_id }}.txt
          echo "✅ All performance tests completed successfully!" >> performance-metrics-${{ github.run_id }}.txt
          echo "⏱️ Test execution time: $(date -u -d @$SECONDS +%H:%M:%S)" >> performance-metrics-${{ github.run_id }}.txt
          echo "" >> performance-metrics-${{ github.run_id }}.txt
          echo "🔍 Test Coverage:" >> performance-metrics-${{ github.run_id }}.txt
          echo "- Page load time measurement" >> performance-metrics-${{ github.run_id }}.txt
          echo "- Complete e-commerce flow performance" >> performance-metrics-${{ github.run_id }}.txt
          echo "- Individual element performance" >> performance-metrics-${{ github.run_id }}.txt
          echo "- Multi-product performance validation" >> performance-metrics-${{ github.run_id }}.txt
          
      - name: Upload Performance Metrics
        uses: actions/upload-artifact@v4
        with:
          name: performance-metrics-${{ github.run_id }}
          path: performance-metrics-${{ github.run_id }}.txt
          if-no-files-found: ignore

  # Job para notificações
  notify:
    runs-on: ubuntu-latest
    needs: [cypress-run, performance-tests]
    if: always()
    
    steps:
      - name: Notify Success
        if: needs.cypress-run.result == 'success' && (needs.performance-tests.result == 'success' || needs.performance-tests.result == 'skipped')
        run: |
          echo "🎉 All tests passed successfully!"
          echo "✅ Cypress tests: PASSED"
          echo "✅ Performance tests: PASSED"
          
      - name: Notify Failure
        if: needs.cypress-run.result == 'failure' || needs.performance-tests.result == 'failure'
        run: |
          echo "❌ Some tests failed!"
          echo "Cypress tests: ${{ needs.cypress-run.result }}"
          echo "Performance tests: ${{ needs.performance-tests.result }}"
